export default [
  {
    id: 1,
    name: 'Capstone',
    description: 'This is a project confirming that I have properly understood everything learned so far from the first module.',
    featured: 'project-1-featured',
    image: 'images/capstone.jpg',
    technologies: ['HTML', 'CSS', 'Javascript'],
    liveVersionLink: 'https://fuadnabi.github.io/Week-One-Capstone/',
    linkToSource: 'https://github.com/FuadNabi/Week-One-Capstone',
  },
  {
    id: 2,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-2-featured',
    image: 'images/capstone.jpg',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'Javascript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 3,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-3-featured',
    image: 'images/capstone.jpg',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'Javascript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 4,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-4-featured',
    image: 'images/capstone.jpg',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'Javascript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 5,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-5-featured',
    image: 'images/capstone.jpg',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'Javascript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 6,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-6-featured',
    image: 'images/capstone.jpg',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'Javascript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
];