export default [
  {
    id: 1,
    name: 'Budget Tracker',
    description: 'Budget Tracker is a website that provides a track of daily transactions that helps make wise financial decisions.',
    featured: 'project-1-featured',
    image: 'images/budget-tracker.png',
    technologies: ['Ruby', 'Rails', 'JavaScript'],
    liveVersionLink: 'https://budget-tracker-azmz.onrender.com/',
    linkToSource: 'https://github.com/FuadNabi/budget-tracker',
  },
  {
    id: 2,
    name: 'Chief\'s Masterpieces',
    description: 'Chief\'s Masterpieces - It is a web application that could provide the count of foods category. The app shows the count as per category (route) and all foods from the selected category.',
    featured: 'project-2-featured',
    image: 'images/chef.png',
    technologies: ['React', 'Redux', 'JavaScript'],
    liveVersionLink: 'https://dev--lucky-baklava-595536.netlify.app/',
    linkToSource: 'https://github.com/FuadNabi/third-capstone',
  },
  {
    id: 3,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-3-featured',
    image: 'images/4-project.png',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'JavaScript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 4,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-4-featured',
    image: 'images/4-project.png',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'JavaScript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 5,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-5-featured',
    image: 'images/4-project.png',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'JavaScript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
  {
    id: 6,
    name: 'Project name',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.',
    featured: 'project-6-featured',
    image: 'images/4-project.png',
    technologies: ['HTML/CSS', 'Ruby and Rails', 'JavaScript'],
    liveVersionLink: '#',
    linkToSource: '#',
  },
];